{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rapiclient
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rapiclient_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rapiclient/rapiclient_{{ version }}.tar.gz
  sha256: 8ac59641aed91d13d0086ddb180de1cddf935f0b7388bd2b0793e62c66ade6f6

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-httr
    - r-jsonlite
    - r-yaml
  run:
    - r-base
    - r-httr
    - r-jsonlite
    - r-yaml

test:
  commands:
    - $R -e "library('rapiclient')"           # [not win]
    - "\"%R%\" -e \"library('rapiclient')\""  # [win]

about:
  home: https://github.com/bergant/rapiclient
  license: MIT
  summary: Access services specified in OpenAPI (formerly Swagger) format. It is not a code generator. Client is generated dynamically as a list of R functions.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rapiclient
# Type: Package
# Title: Dynamic OpenAPI/Swagger Client
# Version: 0.1.3
# Authors@R: person("Darko", "Bergant", email = "darko.bergant@gmail.com", role = c("aut", "cre"))
# URL: https://github.com/bergant/rapiclient
# BugReports: https://github.com/bergant/rapiclient/issues
# Description: Access services specified in OpenAPI (formerly Swagger) format. It is not a code generator. Client is generated dynamically as a list of R functions.
# Depends: R (>= 3.3)
# License: MIT + file LICENSE
# Imports: jsonlite, httr, yaml
# LazyData: TRUE
# RoxygenNote: 6.1.1
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2020-01-17 12:36:44 UTC; DarkoB
# Author: Darko Bergant [aut, cre]
# Maintainer: Darko Bergant <darko.bergant@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-01-17 13:10:03 UTC
